[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)"]
categories = []
description = "Automata created for building trading applications"
edition = "2021"
homepage = "https://pzzld.eth.link/"
keywords = ["scsys"]
license = "MIT"
name = "crypto-automata"
repository = "https://github.com/FL03/crypto-automata"
version = "0.1.0"

[[bin]]
bench = false
name = "crypto-automata"
test = false

[dependencies]
glob = "0.3.0"
tokio = { features = ["full"], version = "1.20.1" }

[dependencies.acme]
features = ["full"]
version = "0.2.0"

[dependencies.rs-crypto-sdk]
path = "../lib"

[dependencies.scsys]
features = ["full"]
version = "0.1.12"