tasks:
  - init: |
      sudo apt install -y clang protobuf-compiler
      rustup default nightly
      rustup target add wasm32-unknown-unknown wasm32-wasi --toolchain nightly
      cargo build --release --workspace
      cargo build -F wasm --target wasm32-unknown-unknown --release --workspace
    command: cargo watch -x test


