tasks:
  - init: |
      rustup default nightly
      rustup target add wasm32-unknown-unknown wasm32-wasi --toolchain nightly
      cargo build --release --workspace
    command: cargo watch -x test


