.cargo_deploy_template: &cargo-deploy
  stage: publish
  script:
    - cargo login $CARGO_REGISTRY_TOKEN
    - cargo publish --all-features --package decanter-slv  -v
    - cargo publish --all-features --package decanter  -v

.cargo_test_template: &cargo_test
  stage: test
  script:
    - cargo test --all-features --release --verbose --jobs 1

stages:
  - build
  - publish
  - test

variables:
  CARGO_REGISTRY_TOKEN: $CARGO_REGISTRY_TOKEN


stable:rust:
  image: rustlang/rust:stable
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  <<: *cargo_test
  <<: *cargo-deploy

nightly:rust:
  allow_failure: true
  image: rustlang/rust:nightly
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  <<: *cargo_test
  <<: *cargo-deploy
