[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com/FL03)"]
categories = []
description = "This crate implements basic cryptographic primitives native to the ecosystem"
edition = "2021"
homepage = "https://github.com/FL03/decanter/wiki"
keywords = []
license = "Apache-2.0"
name = "decanter"
repository = "https://github.com/FL03/decanter"
version = "0.1.2"

[features]
default = ["crypto"]
full = ["crypto", "derive"]

crypto = ["decanter-crypto/default"]
derive = ["decanter-derive"]

wasm = []

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[dev-dependencies]
scsys = "0.1.40"
serde = { features = ["derive"], version = "1" }

[dependencies]
decanter-crypto = { features = ["wasm"], optional = true, path = "../crypto", version = "0.1.2" }
decanter-derive = { optional = true, path = "../derive", version = "0.1.2" }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
