[package]
categories = []
description = "This crate implements basic cryptographic primitives native to the ecosystem"
keywords = []
name = "decanter"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["crypto"]
full = ["crypto", "derive"]

crypto = ["decanter-crypto/default"]
derive = ["decanter-derive"]

wasm = ["decanter-crypto/wasm"]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[dev-dependencies]
scsys = "0.1.40"
serde.workspace = true

[dependencies]
decanter-crypto = { features = ["wasm"], optional = true, path = "../crypto", version = "0.1.3" }
decanter-derive = { optional = true, path = "../derive", version = "0.1.3" }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
