[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com/FL03)"]
categories = []
description = "decanter-crypto implements quantum-resilient cryptographic protocols"
edition = "2021"
homepage = "https://gitlab.com/crsty/crates/decanter/-/wiki"
keywords = ["cryptography"]
license = "MIT"
name = "decanter-crypto"
readme = "README.md"
repository = "https://gitlab.com/crsty/crates/decanter"
version = "0.1.0"

[features]
default = [
    "sleeves"
]

sleeves = []

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
serde = { default-features = false, features = ["derive"], version = "1.0.145" }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]