name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches: [ "main", "master", "prod*" ]
    tags: [ "nightly*",  "v*.*.*" ]
  push:
    branches: [ "main", "master", "prod*" ]
    tags: [ "nightly*",  "v*.*.*" ]
  release:
    types: [ created ]
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build -v --workspace
      - run: cargo test --all --all-features -v
  features:
    if: ${{ github.event.inputs.publish }} || ${{ github.event.release.created }}
    name: Features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - decanter-crypto
          - decanter-derive
    steps:
      - uses: actions/checkout@v3
      - name: Publish (${{matrix.package}})
        run: cargo publish --all-features -v -p ${{ matrix.package }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish:
    if: ${{ github.event.inputs.publish }} || ${{ github.event.release.created }}
    name: Publish
    needs: features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish (decanter)
        run: cargo publish --all-features -v -p decanter --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
